name: My Github Actions Workflow
on: [push]

jobs:
  testing_github:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Display repo name
        run: echo This repo is ${{ github.repository }}
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.